name: Main
on:
  - push
jobs:
  migraiton-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: './sql'
          changeLogFile: 'main/create_table_keys.sql'
          username: ${{ secrets.test_username }}
          password: ${{ secrets.test_password }}
          url: ${{ secrets.test_url }}