name: Main
on:
  - push
jobs:
  flyway_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'sql'
          changeLogFile: 'samplechangelog.h2.sql'
          username: ${{ secrets.DB_BUILD_USERNAME }}
          password: ${{ secrets.DB_BUILD_PASSWORD }}
          url: dblevelupinstance.csxil53pu1c8.eu-west-1.rds.amazonaws.com