# Liquibase migration yaml
name: Main
on:
  - push
jobs:
  flyway_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: './sql'
          changeLogFile: 'main/create_table.keys.sql'
          username: ${{ secrets.DB_BUILD_USERNAME }}
          password: ${{ secrets.DB_BUILD_PASSWORD }}
          url: ${{ secrets.JDBC_DB_URL }}